### ISSUE TITLE
A Good Place To Start

### ISSUE THREAD

**Issue by CosmicPegasis** [Miszion/PersonDatabase#1]
Hii! I happened to fall upon this repo of yours, and I feel like this would be a good fit for people starting out with OOP and some basics, I want to contribute to this repo. First of I would suggest a simple beginner friendly CMake file to help build the project. Write now I have time on my hands, hence I would love to transform this repo into something great, just waiting for the get go!

**Comment by Miszion** [comment]
Hi Cosmic,

Go for it! This started off as an assignment for school, but feel free to use anything here as needed!
